const patterns = [
    { name: "CRE", imageUrl: "/patterns/p1.png" },
    { name: "CML", imageUrl: "/patterns/p2.png" },
    { name: "CRB", imageUrl: "/patterns/p3.png" },
    { name: "CRM", imageUrl: "/patterns/p4.png" },
    { name: "CR580", imageUrl: "/patterns/p5.png" },
    { name: "CR582", imageUrl: "/patterns/p6.png" },
    { name: "CL", imageUrl: "/patterns/p7.png" },
    { name: "CRA", imageUrl: "/patterns/p8.png" },
    { name: "C-95", imageUrl: "/patterns/p9.png" },
    { name: "CM", imageUrl: "/patterns/p10.png" },
    { name: "CN", imageUrl: "/patterns/p11.png" },
    { name: "CRD", imageUrl: "/patterns/p12.png" },
    { name: "C-100", imageUrl: "/patterns/p13.png" },
    { name: "C4-145", imageUrl: "/patterns/p14.png" },
    { name: "CZ", imageUrl: "/patterns/p15.png" },
    { name: "CRC", imageUrl: "/patterns/p16.png" },
    { name: "CM-115", imageUrl: "/patterns/p17.png" },
    { name: "CRG", imageUrl: "/patterns/p18.png" },
    { name: "CJ", imageUrl: "/patterns/p19.png" },
    { name: "CRH", imageUrl: "/patterns/p20.png" },
    { name: "CK", imageUrl: "/patterns/p21.png" },
    { name: "CRJ", imageUrl: "/patterns/p22.png" },
    { name: "CA", imageUrl: "/patterns/p23.png" },
    { name: "CB", imageUrl: "/patterns/p24.png" },
    { name: "CD", imageUrl: "/patterns/p25.png" },
    { name: "CP", imageUrl: "/patterns/p26.png" },
    { name: "CF", imageUrl: "/patterns/p27.png" },
    { name: "CG", imageUrl: "/patterns/p28.png" },
    { name: "CH", imageUrl: "/patterns/p29.png" },
    { name: "CI", imageUrl: "/patterns/p30.png" },
    { name: "CO", imageUrl: "/patterns/p31.png" },
    { name: "C-130", imageUrl: "/patterns/p32.png" },
    { name: "C11", imageUrl: "/patterns/p33.png" },
    { name: "CQ", imageUrl: "/patterns/p34.png" },
    { name: "C24", imageUrl: "/patterns/p35.png" },
    { name: "CR", imageUrl: "/patterns/p36.png" },
    { name: "CS", imageUrl: "/patterns/p37.png" },
    { name: "CT", imageUrl: "/patterns/p38.png" },
];

export default patterns;
